export function usage(): string {
  return [
    "Lynn CLI",
    "",
    "Usage:",
    "  Lynn version",
    "  Lynn doctor [--offline]",
    "  Lynn \"prompt\"",
    "  cat file.txt | Lynn \"summarize this\"",
    "  Lynn - < file.txt",
    "  Lynn -p \"prompt\" [--mock-brain] [--json]",
    "  Lynn exec \"task\" --json [--mock-brain]",
    "  Lynn chat",
    "  Lynn agents [--json]",
    "  Lynn model [--json]",
    "  Lynn providers [--json]",
    "  Lynn worker run --brief task.md --worktree path --jsonl --mock",
    "  Lynn code \"review the current diff\"",
    "  Lynn see screenshot.png [question]",
    "  Lynn ground screenshot.png \"Submit button\" --json",
    "  Lynn ui2code mockup.png",
    "  Lynn code --list-tools",
    "  Lynn code --tool read_file --path README.md --json",
    "  Lynn sessions list --json",
    "  Lynn sessions show <path>",
    "",
    "Alias:",
    "  lynn is kept as a lowercase compatibility alias.",
    "",
    "Common flags:",
    "  --reasoning auto|off|low|medium|high|xhigh",
    "  --show-reasoning auto|always|never",
    "  --brain-url http://127.0.0.1:8790",
    "  --server-url http://127.0.0.1:3000",
  "  --approval ask|on-failure|never|yolo",
  "  --sandbox read-only|workspace-write|danger-full-access",
  "  --max-steps 1..20",
    "  --save-session --data-dir ~/.lynn",
    "  --agent-command \"custom worker command\"",
  ].join("\n");
}
