import { currentLang } from "./i18n.js";

export function usage(): string {
  if (currentLang() === "zh") {
    return [
      "Lynn CLI",
      "",
      "用法:",
      "  Lynn version",
      "  Lynn doctor [--offline]",
      "  Lynn \"问题\"",
      "  cat file.txt | Lynn \"总结这个文件\"",
      "  Lynn - < file.txt",
      "  Lynn -p \"问题\" [--mock-brain] [--json]",
      "  Lynn exec \"任务\" --json [--mock-brain]",
      "  Lynn chat",
      "  Lynn agents [--json]",
      "  Lynn model [--json]",
      "  Lynn providers [--json]",
      "  Lynn providers presets [--json]",
      "  Lynn providers set",
      "  Lynn providers set --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
      "  Lynn providers set --preset stepfun --api-key <api-key>",
      "  Lynn permissions [--json]",
      "  Lynn permissions set --approval ask|yolo --sandbox workspace-write|danger-full-access",
      "  Lynn worker run --brief task.md --worktree path --jsonl --mock",
      "  Lynn code \"review the current diff\"",
      "  Lynn code --resume <session.jsonl> \"继续上次任务\"",
      "  Lynn see screenshot.png [问题]",
      "  Lynn ground screenshot.png \"提交按钮\" --json",
      "  Lynn ui2code mockup.png",
      "  Lynn code --list-tools",
      "  Lynn code --tool read_file --path README.md --json",
      "  Lynn sessions list --json",
      "  Lynn sessions show <path>",
      "",
      "别名:",
      "  lynn 保留为小写兼容命令。",
      "",
      "常用参数:",
      "  --reasoning auto|off|low|medium|high|xhigh",
      "  --show-reasoning auto|always|never",
      "  --brain-url http://127.0.0.1:8790",
      "  --server-url http://127.0.0.1:3000",
      "  --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
      "  --approval ask|on-failure|never|yolo",
      "  --sandbox read-only|workspace-write|danger-full-access",
      "  --max-steps 1..20",
      "  --save-session --resume <session.jsonl> --data-dir ~/.lynn",
      "  --agent-command \"custom worker command\"",
    ].join("\n");
  }
  return [
    "Lynn CLI",
    "",
    "Usage:",
    "  Lynn version",
    "  Lynn doctor [--offline]",
    "  Lynn \"prompt\"",
    "  cat file.txt | Lynn \"summarize this\"",
    "  Lynn - < file.txt",
    "  Lynn -p \"prompt\" [--mock-brain] [--json]",
    "  Lynn exec \"task\" --json [--mock-brain]",
    "  Lynn chat",
    "  Lynn agents [--json]",
    "  Lynn model [--json]",
    "  Lynn providers [--json]",
    "  Lynn providers presets [--json]",
    "  Lynn providers set",
    "  Lynn providers set --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
    "  Lynn providers set --preset stepfun --api-key <api-key>",
    "  Lynn permissions [--json]",
    "  Lynn permissions set --approval ask|yolo --sandbox workspace-write|danger-full-access",
    "  Lynn worker run --brief task.md --worktree path --jsonl --mock",
    "  Lynn code \"review the current diff\"",
    "  Lynn code --resume <session.jsonl> \"continue the task\"",
    "  Lynn see screenshot.png [question]",
    "  Lynn ground screenshot.png \"Submit button\" --json",
    "  Lynn ui2code mockup.png",
    "  Lynn code --list-tools",
    "  Lynn code --tool read_file --path README.md --json",
    "  Lynn sessions list --json",
    "  Lynn sessions show <path>",
    "",
    "Alias:",
    "  lynn is kept as a lowercase compatibility alias.",
    "",
    "Common flags:",
    "  --reasoning auto|off|low|medium|high|xhigh",
    "  --show-reasoning auto|always|never",
    "  --brain-url http://127.0.0.1:8790",
    "  --server-url http://127.0.0.1:3000",
    "  --base-url https://api.example.com/v1 --api-key <api-key> --model model-id",
    "  --approval ask|on-failure|never|yolo",
    "  --sandbox read-only|workspace-write|danger-full-access",
    "  --max-steps 1..20",
    "  --save-session --resume <session.jsonl> --data-dir ~/.lynn",
    "  --agent-command \"custom worker command\"",
  ].join("\n");
}
